# Generated by Django 4.1.7 on 2023-03-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdatas',
            name='lastcall',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdatas',
            name='nextcall',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
