# Generated by Django 4.1.7 on 2023-03-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custcare', '0002_alter_customerdatas_lastcall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noteofuser', to='custcare.customerdatas')),
            ],
        ),
    ]
