# Generated by Django 4.1.7 on 2023-03-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custcare', '0003_viewnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noteofuser', to='custcare.customerdatas'),
        ),
    ]
