# Generated by Django 4.1.7 on 2023-03-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custcare', '0004_alter_viewnote_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViewNote',
            new_name='Note',
        ),
    ]
