# Generated by Django 4.1.7 on 2023-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custcare', '0005_rename_viewnote_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdatas',
            name='nextcall',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
